// <auto-generated />
using System;
using DataLayer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20190202120702_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Pocos.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<DateTime>("HiringDate");

                    b.Property<DateTime>("LastSkillChangeDate");

                    b.Property<string>("Surname");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new { Id = new Guid("6e1ad796-006d-49e2-818a-e658c1d3c7ef"), FirstName = "Orestis", HiringDate = new DateTime(2019, 2, 2, 14, 7, 2, 358, DateTimeKind.Local), LastSkillChangeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Surname = "Koskoletos" },
                        new { Id = new Guid("db0a2230-07f9-4b4f-b4cb-30d6dbfba90d"), FirstName = "Sila", HiringDate = new DateTime(2019, 2, 2, 14, 7, 2, 358, DateTimeKind.Local), LastSkillChangeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Surname = "Sionti" },
                        new { Id = new Guid("ba9c8a89-d52c-4407-9b81-b308f0f7301d"), FirstName = "Nick", HiringDate = new DateTime(2019, 2, 2, 14, 7, 2, 358, DateTimeKind.Local), LastSkillChangeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Surname = "Halkidakis" }
                    );
                });

            modelBuilder.Entity("DataLayer.Pocos.EmployeeSkill", b =>
                {
                    b.Property<Guid>("EmployeeId");

                    b.Property<Guid>("SkillId");

                    b.HasKey("EmployeeId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("EmployeeSkills");

                    b.HasData(
                        new { EmployeeId = new Guid("6e1ad796-006d-49e2-818a-e658c1d3c7ef"), SkillId = new Guid("2d9bbb18-6807-43a5-b3ca-3520102c0c1e") },
                        new { EmployeeId = new Guid("6e1ad796-006d-49e2-818a-e658c1d3c7ef"), SkillId = new Guid("0aa59d45-5544-481e-a47f-9035e4d087e2") },
                        new { EmployeeId = new Guid("6e1ad796-006d-49e2-818a-e658c1d3c7ef"), SkillId = new Guid("dcb6d0f4-a022-45de-91da-684529af59ae") },
                        new { EmployeeId = new Guid("6e1ad796-006d-49e2-818a-e658c1d3c7ef"), SkillId = new Guid("a8f3caf7-1558-4227-add5-e8d8eba086d7") },
                        new { EmployeeId = new Guid("db0a2230-07f9-4b4f-b4cb-30d6dbfba90d"), SkillId = new Guid("2d9bbb18-6807-43a5-b3ca-3520102c0c1e") },
                        new { EmployeeId = new Guid("db0a2230-07f9-4b4f-b4cb-30d6dbfba90d"), SkillId = new Guid("0aa59d45-5544-481e-a47f-9035e4d087e2") },
                        new { EmployeeId = new Guid("ba9c8a89-d52c-4407-9b81-b308f0f7301d"), SkillId = new Guid("2d9bbb18-6807-43a5-b3ca-3520102c0c1e") }
                    );
                });

            modelBuilder.Entity("DataLayer.Pocos.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new { Id = new Guid("2d9bbb18-6807-43a5-b3ca-3520102c0c1e"), CreationDate = new DateTime(2019, 2, 2, 14, 7, 2, 356, DateTimeKind.Local), Description = "", Name = "C#" },
                        new { Id = new Guid("0aa59d45-5544-481e-a47f-9035e4d087e2"), CreationDate = new DateTime(2019, 2, 2, 14, 7, 2, 357, DateTimeKind.Local), Description = "", Name = "VB.NET" },
                        new { Id = new Guid("dcb6d0f4-a022-45de-91da-684529af59ae"), CreationDate = new DateTime(2019, 2, 2, 14, 7, 2, 357, DateTimeKind.Local), Description = "", Name = "ASP.NET MVC" },
                        new { Id = new Guid("a8f3caf7-1558-4227-add5-e8d8eba086d7"), CreationDate = new DateTime(2019, 2, 2, 14, 7, 2, 357, DateTimeKind.Local), Description = "", Name = "ASP.NET Core MVC" }
                    );
                });

            modelBuilder.Entity("DataLayer.Pocos.EmployeeSkill", b =>
                {
                    b.HasOne("DataLayer.Pocos.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataLayer.Pocos.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
