// <auto-generated />
using System;
using DataLayer.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20190207165425_ChangesLog")]
    partial class ChangesLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayer.Pocos.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<DateTime>("HiringDate");

                    b.Property<DateTime>("LastSkillChangeDate");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new { Id = new Guid("8a2d2062-17df-4ed1-92ea-cf4969cc65a7"), FirstName = "Orestis", HiringDate = new DateTime(2019, 2, 7, 18, 54, 25, 723, DateTimeKind.Local), LastSkillChangeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Surname = "Koskoletos" },
                        new { Id = new Guid("5fb4d3e0-d6ec-4eef-afd4-40c760196ac6"), FirstName = "John", HiringDate = new DateTime(2019, 2, 7, 18, 54, 25, 723, DateTimeKind.Local), LastSkillChangeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Surname = "Doe" },
                        new { Id = new Guid("7372bc8b-1492-4fe8-8370-fba1e40278b6"), FirstName = "Jane", HiringDate = new DateTime(2019, 2, 7, 18, 54, 25, 723, DateTimeKind.Local), LastSkillChangeDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), Surname = "Doe" }
                    );
                });

            modelBuilder.Entity("DataLayer.Pocos.EmployeeChangesLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Entity");

                    b.Property<DateTime>("LogStamp");

                    b.Property<string>("Message");

                    b.Property<string>("NewValue");

                    b.Property<string>("OldValue");

                    b.HasKey("Id");

                    b.ToTable("EmployeeChangesLogs");
                });

            modelBuilder.Entity("DataLayer.Pocos.EmployeeSkill", b =>
                {
                    b.Property<Guid>("EmployeeId");

                    b.Property<Guid>("SkillId");

                    b.HasKey("EmployeeId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("EmployeeSkills");

                    b.HasData(
                        new { EmployeeId = new Guid("8a2d2062-17df-4ed1-92ea-cf4969cc65a7"), SkillId = new Guid("e19105bc-f055-4a41-8329-d2eceab90ae3") },
                        new { EmployeeId = new Guid("8a2d2062-17df-4ed1-92ea-cf4969cc65a7"), SkillId = new Guid("c5826822-59e7-4380-9189-a08adc5b6b8a") },
                        new { EmployeeId = new Guid("8a2d2062-17df-4ed1-92ea-cf4969cc65a7"), SkillId = new Guid("c69cff2f-74e6-4f47-bc74-6658167491ae") },
                        new { EmployeeId = new Guid("8a2d2062-17df-4ed1-92ea-cf4969cc65a7"), SkillId = new Guid("3faa7f05-b454-4f12-acbc-87f26978f7a4") },
                        new { EmployeeId = new Guid("5fb4d3e0-d6ec-4eef-afd4-40c760196ac6"), SkillId = new Guid("e19105bc-f055-4a41-8329-d2eceab90ae3") },
                        new { EmployeeId = new Guid("5fb4d3e0-d6ec-4eef-afd4-40c760196ac6"), SkillId = new Guid("c5826822-59e7-4380-9189-a08adc5b6b8a") },
                        new { EmployeeId = new Guid("7372bc8b-1492-4fe8-8370-fba1e40278b6"), SkillId = new Guid("e19105bc-f055-4a41-8329-d2eceab90ae3") }
                    );
                });

            modelBuilder.Entity("DataLayer.Pocos.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new { Id = new Guid("e19105bc-f055-4a41-8329-d2eceab90ae3"), CreationDate = new DateTime(2019, 2, 7, 18, 54, 25, 722, DateTimeKind.Local), Description = "Programming language", Name = "C#" },
                        new { Id = new Guid("c5826822-59e7-4380-9189-a08adc5b6b8a"), CreationDate = new DateTime(2019, 2, 7, 18, 54, 25, 723, DateTimeKind.Local), Description = "Programming language", Name = "VB.NET" },
                        new { Id = new Guid("c69cff2f-74e6-4f47-bc74-6658167491ae"), CreationDate = new DateTime(2019, 2, 7, 18, 54, 25, 723, DateTimeKind.Local), Description = "Framework", Name = "ASP.NET MVC" },
                        new { Id = new Guid("3faa7f05-b454-4f12-acbc-87f26978f7a4"), CreationDate = new DateTime(2019, 2, 7, 18, 54, 25, 723, DateTimeKind.Local), Description = "Framework", Name = "ASP.NET Core MVC" },
                        new { Id = new Guid("1cfcc2fe-20e9-420d-b331-dc045ebb9c5a"), CreationDate = new DateTime(2019, 2, 7, 18, 54, 25, 723, DateTimeKind.Local), Description = "Programming language", Name = "Python" }
                    );
                });

            modelBuilder.Entity("DataLayer.Pocos.EmployeeSkill", b =>
                {
                    b.HasOne("DataLayer.Pocos.Employee", "Employee")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataLayer.Pocos.Skill", "Skill")
                        .WithMany("EmployeeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
